replicaCount: 2

image:
  repository: nginx
  tag: "1.27"

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  host: demo-stage.local

vault:
  path: secret
  role: vault-stage

secrets:
  enabled: true
  vaultPath: stage/app
  vaultRole: stage
  serviceAccountName: vault-stage