apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform
spec:
  description: TODO app only (dev / stage / prod)
  sourceRepos:
    - https://github.com/AtulFalle/k8s-infra.git
  destinations:
    - namespace: todo-dev
      server: https://kubernetes.default.svc
    - namespace: todo-stage
      server: https://kubernetes.default.svc
    - namespace: todo-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
