replicaCount: 3

image:
  repository: nginx
  tag: "1.27"

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  host: demo.prod

vault:
  path: secret
  role: vault-prod

secrets:
  enabled: true
  vaultPath: prod/app
  vaultRole: prod
  serviceAccountName: vault-prod