kind: ExternalSecret
apiVersion: external-secrets.io/v1
metadata:
  name: app-secrets
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: app-secrets
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: dev/app
        property: DB_HOST

    - secretKey: DB_NAME
      remoteRef:
        key: dev/app
        property: DB_NAME

    - secretKey: DB_USER
      remoteRef:
        key: dev/app
        property: DB_USER

    - secretKey: DB_PASSWORD
      remoteRef:
        key: dev/app
        property: DB_PASSWORD