{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault
    kind: SecretStore

  target:
    name: {{ .Release.Name }}-secrets

  data:
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.secrets.vaultPath }}
        property: DB_HOST

    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.secrets.vaultPath }}
        property: DB_NAME

    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.secrets.vaultPath }}
        property: DB_USER

    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.vaultPath }}
        property: DB_PASSWORD
{{- end }}