{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.secrets.vaultRole | quote }}
          serviceAccountRef:
            name: {{ .Values.secrets.serviceAccountName }}
{{- end }}