apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/instance: demo-app-dev
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io/cascade
spec:
  project: workloads
  source:
    repoURL: https://github.com/AtulFalle/k8s-infra.git
    targetRevision: HEAD
    path: charts/app
    helm:
      releaseName: demo-app-dev
      valueFiles:
        - ../../envs/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
