apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: todo
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io/cascade
spec:
  project: workloads
  # Prod: manual sync for POC (promote via Git tag change, then sync in UI/CLI)
  source:
    repoURL: https://github.com/AtulFalle/k8s-infra.git
    targetRevision: HEAD
    path: charts/todo
    helm:
      releaseName: todo
      valueFiles:
        - ../../envs/todo/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
