replicaCount: 1

image:
  repository: atulfalle1815/todo
  tag: "0.1.2"
  pullPolicy: Always

imagePullSecrets: []

serviceAccount:
  name: vault-todo

config:
  APP_ENV: prod

secrets:
  enabled: true
  vaultPath: prod/todo
  vaultRole: todo-prod

ingress:
  enabled: true
  className: nginx
  host: todo-prod.local

persistence:
  enabled: true
  size: 1Gi

cronjobs:
  cleanup:
    enabled: true
    schedule: "0 * * * *"
  digest:
    enabled: true
    schedule: "0 6 * * *"
