kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: demo-app-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AtulFalle/k8s-infra.git
    targetRevision: HEAD
    path: charts/app
    helm:
      valueFiles:
      - ../envs/stage/Values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true