replicaCount: 1

image:
  repository: atulfalle1815/todo
  tag: "sha-9cb3654"
  pullPolicy: Always

imagePullSecrets:
  - name: dockerhub

serviceAccount:
  name: vault-todo

config:
  APP_ENV: dev
  APP_VERSION: "sha-9cb3654"

secrets:
  enabled: true
  vaultPath: dev/todo
  vaultRole: todo-dev

ingress:
  enabled: true
  className: nginx
  host: todo-dev.local

persistence:
  enabled: true
  size: 1Gi

cronjobs:
  cleanup:
    enabled: true
    schedule: "*/5 * * * *"
  digest:
    enabled: true
    schedule: "*/15 * * * *"
  # Enable to test Grafana job-failure alert in dev
  fail-once:
    enabled: false
    schedule: "*/30 * * * *"
