replicaCount: 1

image:
  repository: atulfalle1815/todo
  tag: "sha-9e9d580"
  pullPolicy: Always

imagePullSecrets:
  - name: dockerhub

serviceAccount:
  name: vault-todo

config:
  APP_ENV: dev
  APP_VERSION: "sha-9e9d580"

secrets:
  enabled: true
  vaultPath: dev/todo
  vaultRole: todo-dev

ingress:
  enabled: true
  className: nginx
  host: todo-dev.local

persistence:
  enabled: true
  size: 1Gi
