{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "todo.fullname" . }}-secrets
  labels:
    {{- include "todo.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval }}
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: {{ include "todo.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.secrets.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.secrets.vaultPath }}
        property: {{ . }}
    {{- end }}
{{- end }}
