{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
  labels:
    {{- include "todo.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    vault:
      server: {{ .Values.secrets.vaultServer | quote }}
      path: {{ .Values.secrets.vaultMount | quote }}
      version: "v2"
      auth:
        kubernetes:
          mountPath: {{ .Values.secrets.vaultAuthMount | quote }}
          role: {{ .Values.secrets.vaultRole | quote }}
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name | quote }}
{{- end }}
